export const PUBLICATIONS_FAILURE = 'PUBLICATIONS_FAILURE';
export const PUBLICATIONS_SUCCESS = 'PUBLICATIONS_SUCCESS';
export const PUBLICATIONS_REQUEST = 'PUBLICATIONS_REQUEST';
export const CLEAR_PUBLICATIONS = "CLEAR_PUBLICATIONS";
