# Generated by Django 2.1.8 on 2019-05-05 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='publications',
            options={'verbose_name': 'publication', 'verbose_name_plural': 'publications'},
        ),
        migrations.AddField(
            model_name='publications',
            name='is_premium',
            field=models.BooleanField(default=True, verbose_name='is premium'),
        ),
        migrations.AlterField(
            model_name='publicationpicture',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='publications.Publications'),
        ),
    ]
