# Generated by Django 2.2.4 on 2019-11-12 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20190505_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='is premium'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='users.Profile'),
        ),
    ]
